name: Generate Changelog

on:
 push:
  branches: '*'
 pull_request:
    types:
      - closed

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install conventional-changelog
        run: npm install -g conventional-changelog-cli

      - name: Generate Changelog
        run: conventional-changelog -p angular -i CHANGELOG.md -s -r 0
