name: Release Changelog
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  release-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          fromTag: v1.0.0
          toTag: v2.0.0
          outputFile: CHANGELOG.md
