name: Generate Changelog

on:
  push: 
   branches: '*'
  pull_request:
    types:
      - opened
      - closed

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install release-changelog-builder
        run: npm install release-changelog-builder

      - name: Generate Changelog
        run: npx release-changelog-builder --output-file CHANGELOG.md --token ${{ secrets.GITHUB_TOKEN }}
