name: Generate Changelog

on:
  push:
   branches: '*'
  pull_request:
    types:
      - closed

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: yarn install
      - run: yarn changelog
        with:
          file: CHANGELOG.md
          pull_request: ${{ github.event.pull_request.number }}
