name: Release Changelog 2
on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main
  

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          fromTag: ${{ github.event.pull_request.base.sha }}
          toTag: ${{ github.event.pull_request.head.sha }}
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: ${{ steps.github_release.outputs.changelog }}
          draft: false
          prerelease: false
