name: main5

on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: release-changelog-builder/release-changelog-builder@v1
        with:
          repo: ${{ github.repository }}
          branch: main
          file: CHANGELOG.md
