name: Publish

on:
 workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

        
      - name: Release
        id: create_release
        
        uses: actions/create-release@v1.0.0
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ steps.autotagger.outputs.tagname }}
          release_name: Version ${{ steps.autotagger.outputs.version }}
          body: ${{ steps.autotagger.outputs.tagmessage }}
          draft: false
          prerelease: true


      - name: Rollback Release
       
        uses: author/action-rollback@stable
        with:
          # Using a known release ID
          id: ${{ steps.create_release.id }}
          # Using a tag name
          tag: ${{ steps.autotagger.outputs.tagname }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
