name: Release and Rollback

on:
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v2.3.0
        env: 
          GH_PAT: ${{ secrets.GH_PAT }}
        with:   
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          draft: false
          prerelease: false

  rollback:
    name: Rollback Release
    needs: release
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Release
        uses: author/action-rollback@stable
        with:
          # Using a known release ID
          release_id: ${{ needs.release.id }}
          # Using a tag name
          tag: ${{ needs.release.outputs.tag }}
          # If the release does not exist but the tag does, setting this to true will remove the tag.
         # delete_orphan_tag: true
        env: 
         GH_PAT: ${{ secrets.GH_PAT }}
